run:
  timeout: 5m
  skip-dirs:
    - \.git
    - node_modules
    - vendor
    - \.tmp
    - target
issues:
  exclude-dirs:
    - \.git
    - node_modules
    - vendor
    - \.tmp
    - target
linters:
  enable:
    - funlen
    - gocyclo
    - gocognit
    - nestif
    - gosec
    - gofmt
    - goimports
    - errcheck
linters-settings:
  funlen:
    lines: 50
    statements: 40
  gocyclo:
    min-complexity: 8
  gocognit:
    min-complexity: 15
  nestif:
    min-complexity: 4
  lll:
    line-length: 120
